[package]
name = "video-toolbox-sys"
version = "0.1.0"
edition = "2018"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
description = "Bindings to VideoToolBox for OS X and iOS"
license = "MIT"
homepage   = "https://github.com/luozijun/rust-videotoolbox-sys"
repository = "https://github.com/luozijun/rust-videotoolbox-sys"
documentation = "https://docs.rs/videotoolbox-sys/*/x86_64-apple-darwin/videotoolbox_sys"


[dependencies]
libc = "0.2"
core-foundation-sys = "0.8"
core-media-sys = "0.1.0"
core-video-sys = "0.2.0"

[dev-dependencies]
core-foundation = "0.6"

[patch.crates-io]
core-video-sys = { git = "https://github.com/AstroHQ/core-video-sys" }
